# Generated by Django 5.1.11 on 2025-08-24 13:55

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import taggit.managers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Contact name", max_length=100)),
                ("email", models.EmailField(help_text="Contact email", max_length=254)),
                (
                    "subject",
                    models.CharField(help_text="Message subject", max_length=200),
                ),
                ("message", models.TextField(help_text="Message content")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(db_index=True, max_length=200)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Search Analytics",
                "verbose_name_plural": "Search Analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Platform name (e.g., GitHub, Twitter)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug (e.g., github, twitter)", unique=True
                    ),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        blank=True,
                        help_text="URL pattern (use {username} placeholder, e.g., https://github.com/{username})",
                        max_length=200,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class (e.g., fab fa-github)",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Brand color (Hex code, e.g., #333333)",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active status"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Social Media Platform",
                "verbose_name_plural": "Social Media Platforms",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Description for search engines (max 160 characters)",
                        max_length=160,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="Category introduction text"
                    ),
                ),
                (
                    "show_in_navigation",
                    models.BooleanField(
                        default=True, help_text="Show in navigation menu"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in navigation"
                    ),
                ),
                (
                    "category_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category banner image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Page",
                "ordering": ["order", "title"],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Description for search engines (max 160 characters)",
                        max_length=160,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Publication date"
                    ),
                ),
                (
                    "event_start_at",
                    models.DateTimeField(
                        blank=True, help_text="Event start date and time", null=True
                    ),
                ),
                (
                    "event_end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Event end date and time (optional)",
                        null=True,
                    ),
                ),
                (
                    "display_start_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Page display start date and time",
                        null=True,
                    ),
                ),
                (
                    "display_end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Page display end date and time",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Event location", max_length=255
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show as featured content"
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated reading time (minutes)",
                        null=True,
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, help_text="Page view count"),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 0),
                            ("image", 4),
                            ("image_with_text", 9),
                            ("gallery", 15),
                            ("quote", 19),
                            ("code", 23),
                            ("speaker", 28),
                            ("event_registration", 32),
                            ("markdown", 33),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Choose an image to display"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Image caption",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Alternative text for accessibility",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("caption", 2), ("alt_text", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Choose an image"},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Image on Left"),
                                        ("right", "Image on Right"),
                                    ],
                                    "help_text": "Position of the image",
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Section title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Text content"},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 5),
                                        ("image_position", 6),
                                        ("title", 7),
                                        ("text", 8),
                                        ("alt_text", 3),
                                    ]
                                ],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Gallery title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            11: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 11), ("caption", 12), ("alt_text", 12)]],
                                {},
                            ),
                            14: ("wagtail.blocks.ListBlock", (13,), {}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 10), ("images", 14)]],
                                {},
                            ),
                            16: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Quote text"},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Quote author",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Author's title or position",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 16), ("author", 17), ("author_title", 18)]],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("javascript", "JavaScript"),
                                        ("html", "HTML"),
                                        ("css", "CSS"),
                                        ("sql", "SQL"),
                                        ("bash", "Bash"),
                                    ],
                                    "help_text": "Programming language",
                                },
                            ),
                            21: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Code snippet"},
                            ),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Code caption",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 20), ("code", 21), ("caption", 22)]],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Speaker name", "max_length": 255},
                            ),
                            25: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Speaker title/position",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            26: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Speaker bio", "required": False},
                            ),
                            27: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Speaker photo", "required": False},
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 24),
                                        ("title", 25),
                                        ("bio", 26),
                                        ("photo", 27),
                                    ]
                                ],
                                {},
                            ),
                            29: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Registration link URL"},
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Register Now",
                                    "help_text": "Button text",
                                    "max_length": 100,
                                },
                            ),
                            31: (
                                "wagtail.blocks.DateTimeBlock",
                                (),
                                {
                                    "help_text": "Registration deadline",
                                    "required": False,
                                },
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("registration_url", 29),
                                        ("button_text", 30),
                                        ("deadline", 31),
                                    ]
                                ],
                                {},
                            ),
                            33: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                        },
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Page",
                "verbose_name_plural": "Content Pages",
                "ordering": ["-publication_date"],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContentPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="content.contentpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="contentpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="content.ContentPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Description for search engines (max 160 characters)",
                        max_length=160,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="PyLadies Seoul", max_length=255),
                ),
                (
                    "hero_subtitle",
                    wagtail.fields.RichTextField(
                        default="Empowering women in Python development"
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(blank=True, default="Join Us", max_length=100),
                ),
                ("hero_cta_url", models.URLField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero_section", 4),
                            ("featured_events", 7),
                            ("statistics", 14),
                            ("rich_text", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Hero title", "max_length": 255},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Hero subtitle"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Call-to-action button text",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Call-to-action button URL",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("cta_text", 2),
                                        ("cta_url", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Upcoming Events", "max_length": 255},
                            ),
                            6: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 3,
                                    "help_text": "Number of events to show",
                                    "max_value": 6,
                                    "min_value": 1,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 5), ("show_count", 6)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "PyLadies Seoul in Numbers",
                                    "max_length": 255,
                                },
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "e.g., 500+", "max_length": 50},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "e.g., Members", "max_length": 100},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("number", 9), ("label", 10), ("description", 11)]],
                                {},
                            ),
                            13: ("wagtail.blocks.ListBlock", (12,), {}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 8), ("statistics", 13)]],
                                {},
                            ),
                            15: ("wagtail.blocks.RichTextBlock", (), {}),
                        },
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name", max_length=255)),
                (
                    "member_type",
                    models.CharField(
                        choices=[("member", "Member"), ("organizer", "Organizer")],
                        default="member",
                        help_text="Member type",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Role/position (required for organizers)",
                        max_length=255,
                    ),
                ),
                (
                    "bio",
                    wagtail.fields.RichTextField(blank=True, help_text="Biography"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Public email address", max_length=254
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active status"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show as featured on homepage"
                    ),
                ),
                (
                    "show_in_member_list",
                    models.BooleanField(default=True, help_text="Show in member list"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "joined_date",
                    models.DateField(blank=True, help_text="Join date", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profile photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Add tags (e.g., python, django, data-science)",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["member_type", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="contentpage",
            name="related_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Related member (interviewee, speaker, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_pages",
                to="content.member",
            ),
        ),
        migrations.CreateModel(
            name="MemberSnippet",
            fields=[],
            options={
                "verbose_name": "Member/Organizer",
                "verbose_name_plural": "Members/Organizers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.member",),
        ),
        migrations.CreateModel(
            name="SocialMediaPlatformSnippet",
            fields=[],
            options={
                "verbose_name": "Social Media Platform",
                "verbose_name_plural": "Social Media Platforms",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.socialmediaplatform",),
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Viewer IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User Agent information"),
                ),
                ("referrer", models.URLField(blank=True, help_text="Referrer URL")),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key (for duplicate view prevention)",
                        max_length=40,
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, help_text="View timestamp"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Viewed page",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="content.contentpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page View",
                "verbose_name_plural": "Page Views",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["page", "-viewed_at"],
                        name="content_pag_page_id_979c07_idx",
                    ),
                    models.Index(
                        fields=["session_key", "page"],
                        name="content_pag_session_526e60_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Full URL (e.g., https://github.com/username)",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username or ID (if no URL)",
                        max_length=100,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name (uses platform name if empty)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active status"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Social link owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="content.member",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Social media platform",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.socialmediaplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["member", "order", "platform"],
                "unique_together": {("member", "platform")},
            },
        ),
    ]
