# Generated by Django 5.1.11 on 2025-08-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributeMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="제목 (예: 기부, 자원봉사)", max_length=100
                    ),
                ),
                ("description", models.TextField(help_text="설명 내용")),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome 아이콘 클래스 (예: fas fa-heart)",
                        max_length=100,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="자세히 보기 링크 (선택사항)"
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        default="자세히 보기", help_text="링크 텍스트", max_length=50
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="표시 순서"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "기여 방법",
                "verbose_name_plural": "기여 방법들",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ContributeMethodSnippet",
            fields=[],
            options={
                "verbose_name": "기여 방법",
                "verbose_name_plural": "기여 방법들",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.contributemethod",),
        ),
    ]
