# Generated by Django 5.1.11 on 2025-08-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_contributemethod_contributemethodsnippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(help_text="자주 묻는 질문", max_length=255),
                ),
                ("answer", models.TextField(help_text="질문에 대한 답변")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="표시 순서"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "question"],
            },
        ),
        migrations.CreateModel(
            name="FAQSnippet",
            fields=[],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.faq",),
        ),
    ]
