# Generated by Django 5.1.11 on 2025-08-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_faq_faqsnippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="intro",
            field=models.CharField(
                blank=True,
                help_text="Short introduction quote (e.g., 'I started my career to change the world!')",
                max_length=255,
            ),
        ),
    ]
